import requests

url=["https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/css/prettyPhoto.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/fonts/font-awesome.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/css/owl.carousel.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css?ver=5.11.0","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/animations/animations.min.css?ver=3.2.2","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/css/frontend.min.css?ver=3.2.2","https://dsscovidhelp.com/wp-content/uploads/elementor/css/global.css?ver=1619689584","https://dsscovidhelp.com/wp-content/uploads/elementor/css/post-205.css?ver=1619771669","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.1","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min.css?ver=5.15.1","https://dsscovidhelp.com/wp-includes/css/dist/block-library/style.min.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/vendors-style.css?ver=4.7.2","https://dsscovidhelp.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/style.css?ver=4.7.2","https://dsscovidhelp.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.4.1","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=5.2.2","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=5.2.2","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/css/woocommerce.css?ver=5.2.2","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/style.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/style_core.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/css/animate.min.css?ver=5.7.1","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/css/nivo-slider.css?ver=5.7.1"]
url_2=["https://dsscovidhelp.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/complete.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/other.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/jquery.bxslider.min.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/index.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/jquery.quicksand.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/script.js?ver=1", "https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/counterup.min.js?ver=","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/verticalslider.js?ver=","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/jquery.prettyPhoto.js?ver=","https://dsscovidhelp.com/wp-content/themes/skt-sanitization/assets/js/owl.carousel.js?ver=","https://dsscovidhelp.com/wp-content/plugins/contact-form-7/includes/js/index.js?ver=5.4.","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.7","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=5.2.","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min.js?ver=2.1.","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min.js?ver=5.2.","https://dsscovidhelp.com/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=5.2.","https://dsscovidhelp.com/wp-includes/js/hoverIntent.min.js?ver=1.8.","https://dsscovidhelp.com/wp-includes/js/comment-reply.min.js?ver=5.7.","https://dsscovidhelp.com/wp-includes/js/wp-embed.min.js?ver=5.7.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.2.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.2.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/waypoints/waypoints.min.js?ver=4.0.","https://dsscovidhelp.com/wp-includes/js/jquery/ui/core.min.js?ver=1.12.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js?ver=5.3.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/share-link/share-link.min.js?ver=3.2.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/lib/dialog/dialog.min.js?ver=4.8.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.2.","https://dsscovidhelp.com/wp-content/plugins/elementor/assets/js/preloaded-modules.min.js?ver=3.2.","https://dsscovidhelp.com/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=7.4.4"]
for i in range(0,len(url_2)):
    print(url_2[i])
    r= requests.get(url_2[i])
    data=r.content
    with open('action.txt','a') as out:
        out.writelines(str(data))
        out.write("\n")
        out.close()
        print(i,len(url_2))